services:
  # Backend Service
  - type: web
    name: oratio-backend
    runtime: docker
    plan: standard
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: FLASK_DEBUG
        value: "0"

  # Frontend Service
  - type: web
    name: oratio-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: out
    rootDir: client
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          name: oratio-backend
          type: web
          property: host
