services:
  # Backend Service
  - type: web
    name: oratio-backend
    runtime: docker
    plan: standard
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: FLASK_DEBUG
        value: "0"
    buildCommand: docker build -t oratio-backend .
    startCommand: gunicorn --bind 0.0.0.0:$PORT --timeout 600 app:app

  # Frontend Service
  - type: static
    name: oratio-frontend
    runtime: node
    buildCommand: npm run build
    publishPath: out
    rootDir: client
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          name: oratio-backend
          type: web
          property: host
